# Generated by Django 4.2.2 on 2023-09-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='featured_artist',
            field=models.ManyToManyField(blank=True, related_name='feature_music', to='Music.artist'),
        ),
    ]
