# Generated by Django 4.2.2 on 2023-10-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_profile_playlist_musichistory_lyric_music_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='music_like', to='Music.profile'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='music',
            field=models.ManyToManyField(blank=True, related_name='playlist', to='Music.music'),
        ),
    ]
