# Generated by Django 4.2.2 on 2023-10-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0004_alter_music_like_alter_playlist_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='', max_length=1000000, verbose_name='PlayList Name'),
        ),
    ]
