# Generated by Django 4.2.2 on 2023-10-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0005_playlist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
