# Generated by Django 4.2.2 on 2023-10-30 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0008_alter_musichistory_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musichistory',
            name='music',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='music_history', to='Music.music'),
        ),
    ]
