# Generated by Django 4.2.2 on 2023-11-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0009_alter_musichistory_music'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='cover_photo',
        ),
    ]
