# Generated by Django 4.2.2 on 2024-09-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0010_remove_playlist_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
